export * from "./EmailIcon";
export * from "./PhoneIcon";
export * from "./ChevronRightIcon";
export * from "./OfficeIcon";
export * from "./DirectionIcon";
export * from "./ChevronDownIcon";
export * from "./CloseIcon";
export * from "./MenuIcon";
export * from "./BusinessChipIcon";
export * from "./FoundationIcon";
export { default as RestaurantFeatureIcon } from './RestaurantFeatureIcon';
